# The service providing the commit statuses to GitHub.
status = [
  "buildbot/buildbot-build-script"
]

# Allow eight hours for builds + tests.
timeout_sec = 28800

# Have bors delete auto-merged branches
delete_merged_branches = true
