# The service providing the commit statuses to GitHub.
status = [
  "buildbot/buildbot-build-script"
]

# Allow two hours for builds.
timeout_sec = 7200

# Have bors delete auto-merged branches
delete_merged_branches = true
